<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select</name>
   <tag></tag>
   <elementGuidId>5541475b-595b-4f8b-885e-c76705e1efd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#head</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='head']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1. Head:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>de99c570-4bf4-46d6-8d64-d5b5ca1ede02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>head</value>
      <webElementGuid>fb74fdf8-ecbe-4d1f-8b36-304ea961a93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>head</value>
      <webElementGuid>884763af-9e71-4145-abf3-36c500864e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-select</value>
      <webElementGuid>b310ff77-a6cb-41a1-8601-e55e26159c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Choose a head --Roll-a-thor headPeanut crusher headD.A.V.E headAndy Roid headSpanner mate headDrillbit 2000 head</value>
      <webElementGuid>6b519949-53c7-4422-b4b2-6ab8935fe8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;head&quot;)</value>
      <webElementGuid>57fa39f7-2c1e-4ebd-b9df-e6c954d10bc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='head']</value>
      <webElementGuid>06373709-109d-4920-ab2d-ca2e2bdb3c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/form/div/select</value>
      <webElementGuid>ba1e6e7e-e9dc-41c0-959d-51081e57fde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='are'])[1]/following::select[1]</value>
      <webElementGuid>cee469cf-037a-4d95-b33d-d375cfa125c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Build and order your robot!'])[1]/following::select[1]</value>
      <webElementGuid>150c31b2-4e52-4c55-9e1c-45a29558cdec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roll-a-thor body'])[1]/preceding::select[1]</value>
      <webElementGuid>c2cd6eed-cab3-4737-b569-a6c502fbf962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peanut crusher body'])[1]/preceding::select[1]</value>
      <webElementGuid>4706940d-3de0-4605-aa1e-f4ca5cf2ef22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c05073f7-69db-4549-b644-7d919cdfa7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'head' and @name = 'head' and (text() = '-- Choose a head --Roll-a-thor headPeanut crusher headD.A.V.E headAndy Roid headSpanner mate headDrillbit 2000 head' or . = '-- Choose a head --Roll-a-thor headPeanut crusher headD.A.V.E headAndy Roid headSpanner mate headDrillbit 2000 head')]</value>
      <webElementGuid>e1434dd9-812a-4200-a981-d56ec7ba8742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
